### ISSUE TITLE
Getting NullPointerException

### ISSUE THREAD

**Issue by Android1500** [mywalkb/ApiModuleTest#1]
'java.lang.String io.github.xposed.xposedservice.IXposedService.getXposedVersionName()' on a null object reference

I get this exception while click on button even if i added after null check

**Comment by mywalkb** [comment]
Have you enabled the example module?
If the module is not enabled, the hook is not set and `getSystemService("LSPosed")` return null.
There is not the check on NPE but works when the module is enabled.

**Comment by Android1500** [comment]
Yah i enabled example module in lsposed but still app crash and giving nullpoint exception even i try reboot after enable but nothing works.

**Comment by mywalkb** [comment]
Are you using my mod of LSPosed mywalkb/LSPosed_mod?
If yes can you install debug version and post logcat output?

**Comment by Android1500** [comment]
I am not using LSPosed_mod btw i have one more question after enable it which app should i select in lsposed for scope?

**Comment by mywalkb** [comment]
> I am not using LSPosed_mod

This module works only with LSPosed_mod. In my mod a hook in set on getSystemService, so it return a binder.

any doesn't matter. It is important that the module is enabled. If you don't select an app, the module is automatically disabled when you come back.

**Comment by Android1500** [comment]
> any doesn't matter. It is important that the module is enabled. If you don't select an app, the module is automatically disabled when you come back.

Thanks then i did all things correctly.....have you test it yourself its works for you?

**Comment by mywalkb** [comment]
Yes with my mod LSPosed_mod works.

**Comment by Android1500** [comment]
> Yes with my mod LSPosed_mod works.

yah i just tested with LSPosed_mod and its working without crash.
